/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author BRUNO BELTRE GUZMAN
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    Colores colores = new Colores();

    public Ventana() {
        initComponents();
        initComponents2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initComponents2(){
        this.setSize(1050, 600);
        this.setTitle("CRUD And Data Access Object ");
        this.setLocationRelativeTo(null); 
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texApellido = new javax.swing.JTextField();
        texEdad = new javax.swing.JTextField();
        texCurso = new javax.swing.JTextField();
        texBuscar = new javax.swing.JTextField();
        texNombre = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        texResultado = new javax.swing.JLabel();
        cbBuscar = new javax.swing.JComboBox<>();
        btnBruscar = new javax.swing.JButton();
        texId = new javax.swing.JLabel();
        texId1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(colores.getFondo1());
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1026, 554));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(colores.getFondo1());
        jPanel4.setPreferredSize(new java.awt.Dimension(1026, 534));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(colores.getFondo1());
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1026, 534));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Apellido: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Edad: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Curso: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Nombre: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        texApellido.setBackground(colores.getGris1());
        texApellido.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        texApellido.setForeground(new java.awt.Color(204, 204, 204));
        texApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        texApellido.setCaretColor(null);
        jPanel1.add(texApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 320, 35));

        texEdad.setBackground(colores.getGris1());
        texEdad.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        texEdad.setForeground(new java.awt.Color(204, 204, 204));
        texEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        texEdad.setCaretColor(null);
        jPanel1.add(texEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 320, 35));

        texCurso.setBackground(colores.getGris1());
        texCurso.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        texCurso.setForeground(new java.awt.Color(204, 204, 204));
        texCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        texCurso.setCaretColor(null);
        jPanel1.add(texCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 320, 35));

        texBuscar.setBackground(colores.getGris1());
        texBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        texBuscar.setForeground(new java.awt.Color(204, 204, 204));
        texBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        texBuscar.setCaretColor(null);
        jPanel1.add(texBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 480, 35));

        texNombre.setBackground(colores.getGris1());
        texNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        texNombre.setForeground(new java.awt.Color(204, 204, 204));
        texNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        texNombre.setCaretColor(null);
        jPanel1.add(texNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 320, 35));

        btnModificar.setBackground(colores.getColorPrymary());
        btnModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 120, 35));

        btnEliminar.setBackground(colores.getColorPrymary());
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 120, 35));

        btnLimpiar.setBackground(colores.getColorPrymary());
        btnLimpiar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Linpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 120, 35));

        btnRegistrar.setBackground(colores.getColorPrymary());
        btnRegistrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 120, 35));

        Table.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Edad", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setMinimumSize(new java.awt.Dimension(0, 0));
        Table.setSelectionBackground(colores.getColorPrymary());
        Table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Table.setFocusable(false);
        Table = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 610, 350));

        texResultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        texResultado.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(texResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 610, 30));

        cbBuscar.setBackground(colores.getGris1());
        cbBuscar.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        cbBuscar.setForeground(new java.awt.Color(255, 255, 255));
        cbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nombre", "Apellido", "Edad", "Curso" }));
        cbBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(cbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 30));

        btnBruscar.setBackground(colores.getColorPrymary());
        btnBruscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBruscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBruscar.setText("Buscar");
        jPanel1.add(btnBruscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 110, 35));

        texId.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        texId.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(texId, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 170, 30));

        texId1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        texId1.setForeground(new java.awt.Color(204, 204, 204));
        texId1.setText("ID:");
        jPanel1.add(texId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 30, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        jPanel4.add(jPanel1, gridBagConstraints);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(colores.getFondo1());
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1026, 20));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("2020 BrunoDev, All Copyright ©");
        jLabel6.setPreferredSize(new java.awt.Dimension(800, 20));
        jPanel3.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBruscar() {
        return btnBruscar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public JComboBox<String> getCbBuscar() {
        return cbBuscar;
    }

    public JTable getTable() {
        return Table;
    }

    public JTextField getTexApellido() {
        return texApellido;
    }

    public JTextField getTexBuscar() {
        return texBuscar;
    }

    public JTextField getTexCurso() {
        return texCurso;
    }

    public JTextField getTexEdad() {
        return texEdad;
    }

    public JTextField getTexNombre() {
        return texNombre;
    }

    public JLabel getTexResultado() {
        return texResultado;
    }

    public JLabel getTexId() {
        return texId;
    }

    /**
     * Metodos Setters y Getters
     */

    /**
     * Metodos Setters y Getters
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnBruscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField texApellido;
    private javax.swing.JTextField texBuscar;
    private javax.swing.JTextField texCurso;
    private javax.swing.JTextField texEdad;
    private javax.swing.JLabel texId;
    private javax.swing.JLabel texId1;
    private javax.swing.JTextField texNombre;
    private javax.swing.JLabel texResultado;
    // End of variables declaration//GEN-END:variables

}
